version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    container_name: backend-app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/express-mvc-base}
    depends_on:
      - mongodb
volumes:
  mongo-data: